poor_rg        = "Trial"
poor_loc       = "West Europe"
virt           = "virtual"
add_space      = ["10.0.0.0/16"]
sub            = "V-sub"
pre_add_space  = ["10.0.2.0/24"]
nic            = "V-net"
IP_config_name = "internal"
IP_allocation  = "Dynamic"
linux_name     = "Jenkins"
size           = "Standard_B1s"
admin          = "root"